server:
  port: 88
  servlet:
    context-path: /common-service

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  devtools:
    restart:
      enabled: true # 热部署开关，false即不启用热部署
      exclude: test/** # 指定目录不更新
#         additional-paths: src/main/java # 指定热部署的目录
  h2:
    console:
      enabled: true #在浏览器中开启H2控制台 http://localhost:88/common-service/h2-console
  main:
    allow-bean-definition-overriding: true
# Redis数据库索引（默认为0）
  redis:
    database: 0
# Redis服务器地址
    host: 127.0.0.1
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
    password: null
# 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 200
# 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
# 连接池中的最大空闲连接
      max-idle: 10
# 连接池中的最小空闲连接
      min-idle: 0
# 连接超时时间（毫秒）
    timeout: 1000
  data:
    mongodb:
      uri: mongodb://localhost:27017/common
logging:
# log logging.path he logging.file 同时配置只会生效一个
  path: /opt/log/common-service/
  file: /opt/log/common-service/common-service.log
  level:
    root: DEBUG
ssh:
#      org:
#         hibernate: DEBUG
# ssh
  host: 127.0.0.1
  username: root
  password: 123/abc
  port: 22
ftp:
# ftp
  host: 127.0.0.1
  port: 21
  username: null
  password: null
mybatis:
  type-aliases-package: com.ibm.common.service.entity
mq:
# MQ
  rocketmq:
    producer-group: please_rename_unique_group_name
    namesrv-addr: localhost:9876
    retry: 0