server:
   port: 80
   servlet:
      context-path: /common-service
spring:
   devtools:
      restart:
         enabled: true # 热部署开关，false即不启用热部署
         exclude: test/** # 指定目录不更新
#         additional-paths: src/main/java # 指定热部署的目录
   h2:
      console:
         enabled: true #在浏览器中开启H2控制台 http://localhost/common-service/h2-console
   main:
      allow-bean-definition-overriding: true
logging:
   level:
      org:
         hibernate: DEBUG
#ssh
ssh:
   host: 127.0.0.1
   username: root
   password: 123/abc
   port: 22
#ftp
ftp:
   host: 127.0.0.1
   port: 21
   username: null
   password: null