
server:
   port: 80
   servlet:
      context-path: /common-service

# 热部署开关，false即不启用热部署
spring:
   devtools:
      restart:
         enabled: true
# 指定热部署的目录
#         additional-paths: src/main/java
# 指定目录不更新
         exclude: test/**
   main:
      allow-bean-definition-overriding: true

#ssh
ssh:
   host: 127.0.0.1
   username: root
   password: 123/abc
   port: 22

#ftp
ftp:
   host: 127.0.0.1
   port: 21
   username: 
   password: 